FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY biometric_data_service.py .
COPY .env .

CMD ["python", "biometric_data_service.py"]
